import { NextResponse } from "next/server";
import { format } from "date-fns";
import { requireAdmin } from "@/lib/auth/session";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import {
  buildEnrollmentsXlsx,
  defaultGeneratedHeader,
  type ExportRow,
  type ExportSheet,
} from "@/lib/export/xlsx";
import type { EnrollmentStatus } from "@/db/schema/enums";

export const dynamic = "force-dynamic";

/**
 * Admin-only monthly report — all enrollments created in the given month,
 * grouped by client (one sheet per client). Defaults to the current calendar
 * month; pass `?month=YYYY-MM` to override.
 *
 * Same workbook shape as the per-client export (banner row + 4-column header),
 * just unscoped from client_id.
 */
export async function GET(request: Request) {
  const session = await requireAdmin();
  const supabase = await createSupabaseServerClient();

  const { searchParams } = new URL(request.url);
  const monthParam = searchParams.get("month"); // "YYYY-MM"

  const { start, end, label } = monthRange(monthParam);

  const { data: enrollments, error } = await supabase
    .from("enrollments")
    .select(
      `id, state, status, sub_status, created_at, client_id,
       client:client_id (id, display_name),
       provider:provider_id (id, first_name, last_name, npi),
       group_entity:group_entity_id (id, legal_name),
       payer:payer_id (id, name)`,
    )
    .gte("created_at", start.toISOString())
    .lt("created_at", end.toISOString())
    .is("deleted_at", null)
    .order("client_id");

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  // Latest comment per enrollment, single query.
  const ids = (enrollments ?? []).map((e) => e.id);
  const latestCommentByEnrollment = new Map<string, string>();
  if (ids.length > 0) {
    const { data: comments } = await supabase
      .from("comments")
      .select("enrollment_id, body, created_at")
      .in("enrollment_id", ids)
      .is("deleted_at", null)
      .order("created_at", { ascending: false });
    for (const c of comments ?? []) {
      if (!latestCommentByEnrollment.has(c.enrollment_id)) {
        latestCommentByEnrollment.set(c.enrollment_id, c.body);
      }
    }
  }

  // One sheet per client. Empty result → single placeholder sheet.
  const sheetMap = new Map<string, ExportSheet>();
  for (const e of enrollments ?? []) {
    const client = Array.isArray(e.client) ? e.client[0] : e.client;
    const provider = Array.isArray(e.provider) ? e.provider[0] : e.provider;
    const groupEntity = Array.isArray(e.group_entity) ? e.group_entity[0] : e.group_entity;
    const payer = Array.isArray(e.payer) ? e.payer[0] : e.payer;
    if (!client) continue;

    const sheetName = client.display_name.slice(0, 31);
    const sheetKey = `client:${client.id}`;

    if (!sheetMap.has(sheetKey)) {
      sheetMap.set(sheetKey, {
        sheetName,
        headerLeft: `Client: ${client.display_name}`,
        headerRight: defaultGeneratedHeader(),
        rows: [],
      });
    }

    const subjectLabel = provider
      ? `${provider.first_name} ${provider.last_name}${provider.npi ? ` (NPI ${provider.npi})` : ""}`
      : (groupEntity?.legal_name ?? "Unknown");

    const row: ExportRow = {
      state: e.state,
      payerName: `${payer?.name ?? "—"} — ${subjectLabel}`,
      status: e.status as EnrollmentStatus,
      subStatus: e.sub_status,
      latestComment: latestCommentByEnrollment.get(e.id) ?? null,
    };
    sheetMap.get(sheetKey)!.rows.push(row);
  }

  if (sheetMap.size === 0) {
    sheetMap.set("empty", {
      sheetName: label,
      headerLeft: `Monthly report — ${label}`,
      headerRight: defaultGeneratedHeader(),
      rows: [],
    });
  }

  const buffer = await buildEnrollmentsXlsx({
    bannerText: `Monthly enrollment report — ${label}. Generated by Dastify Credentialing Portal.`,
    sheets: Array.from(sheetMap.values()),
  });

  // Audit the export.
  await supabase.from("activity_events").insert({
    actor_user_id: session.userId,
    action: "export",
    target_table: "enrollments",
    summary: `Monthly report (${label}) — ${enrollments?.length ?? 0} enrollments`,
  });

  const filename = `dastify-monthly-${label.toLowerCase().replace(/\s+/g, "-")}.xlsx`;

  // Copy into a fresh ArrayBuffer for Node 22's strict BodyInit typing.
  const out = new ArrayBuffer(buffer.byteLength);
  new Uint8Array(out).set(buffer);

  return new NextResponse(out, {
    status: 200,
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}

function monthRange(monthParam: string | null): { start: Date; end: Date; label: string } {
  const now = new Date();
  let year = now.getFullYear();
  let monthIdx = now.getMonth(); // 0-11

  if (monthParam && /^\d{4}-\d{2}$/.test(monthParam)) {
    const [y, m] = monthParam.split("-").map((n) => parseInt(n, 10));
    if (y && m) {
      year = y;
      monthIdx = m - 1;
    }
  }

  const start = new Date(year, monthIdx, 1, 0, 0, 0, 0);
  const end = new Date(year, monthIdx + 1, 1, 0, 0, 0, 0);
  const label = format(start, "MMMM yyyy");
  return { start, end, label };
}
